pipeline {
    agent any
    
    tools {
        maven 'maven'
    }

    environment {
        IMAGE_NAME = 'springbootapp'
        IMAGE_TAG = 'latest'
        TENANT_ID = '6bb8aa1e-d7a1-4e0d-aae3-073137d6fded'
        ACR_NAME = "yournamepetclinic"
        ACR_LOGIN_SERVER = 'yournamepetclinic.azurecr.io'
        FULL_IMAGE_NAME = "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
        RG = 'petclinic-rg'
        NAME = 'myAKSCluster'
    }

    stages {

    }
}