pipeline {
    agent any

    tools {
        maven 'maven'
    }

    environment {
        IMAGE_NAME = 'springbootapp'
        IMAGE_TAG = 'latest'
        TENANT_ID = '6bb8aa1e-d7a1-4e0d-aae3-073137d6fded'
        ACR_NAME = "yournamepetclinic"
        ACR_LOGIN_SERVER = 'yournamepetclinic.azurecr.io'
        FULL_IMAGE_NAME = "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
        RG = 'petclinic-rg'
        NAME = 'myAKSCluster'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/bhat0155/enahanced-petclinc-springboot.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn package -f enahanced-petclinc-springboot/pom.xml'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarserver') {
                    withCredentials([string(credentialsId: 'sonar', variable: 'SONAR_TOKEN')]) {
                        sh """
                            mvn sonar:sonar \
                            -f enahanced-petclinc-springboot/pom.xml \
                            -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.organization=bhat0155 \
                            -Dsonar.projectKey=bhat0155_enahanced-petclinc-springboot \
                            -Dsonar.token=\$SONAR_TOKEN \
                            -DskipTests
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true, credentialsId: 'sonar'
                }
            }
        }
    }
}
