pipeline {
    agent any

    tools {
        maven 'maven'
    }

    environment {
        IMAGE_NAME = 'springbootapp'
        IMAGE_TAG = 'latest'
        TENANT_ID = '6bb8aa1e-d7a1-4e0d-aae3-073137d6fded'
        ACR_NAME = "yournamepetclinic"
        ACR_LOGIN_SERVER = 'yournamepetclinic.azurecr.io'
        FULL_IMAGE_NAME = "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
        RG = 'petclinic-rg'
        NAME = 'myAKSCluster'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/bhat0155/enahanced-petclinc-springboot.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn package -f enahanced-petclinc-springboot/pom.xml'
            }
        }
        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'Sonar-scanner'
            }
            steps {
                withSonarQubeEnv('sonarserver') {
                    sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.organization=bhat0155 \
                        -Dsonar.projectName=enahanced-petclinc-springboot \
                        -Dsonar.projectKey=bhat0155_enahanced-petclinc-springboot \
                        -Dsonar.java.binaries=enahanced-petclinc-springboot/target
                    """
                }
            }
        }
    }
}
